#!/bin/sh
# $Id$

PATH=/usr/local/bin:/usr/bin:/bin
TMPDIR=/tmp/statcheck.$$
HEADER=/home/ibl/stats/autoreply
SENDMAIL=/usr/sbin/sendmail
STRIPBOX=/home/ibl/bin/sqlstat.pl

mkdir $TMPDIR
cd $TMPDIR
tee > stats

REPLTO=`head -1 stats | awk '{print $2}'`
COPYTO=commish@ibl.org

echo "To: $REPLTO" >> reply
echo "cc: $COPYTO" >> reply
echo "Subject: GRS Autoreply" >> reply
cat $HEADER >> reply
nice $STRIPBOX < stats >> reply

#if [ -f stripbox.core ]; then
#    echo "stripbox core dump, you probably have a formatting error" >> reply
#    ls -la stripbox.core >> reply
#fi

$SENDMAIL -t < reply

cd /tmp
rm -rf $TMPDIR

